#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Fix Node.js PATH for compatibility
export PATH="/usr/local/opt/node@20/bin:$PATH"

PATH="/usr/local/opt/node@20/bin:$PATH" npx --no-install commitlint --edit "$1"
